### ISSUE TITLE
I have 55.0.2 (64 bits) but it doesn't want to install

### ISSUE THREAD

**Issue by ArfyFR** [pmalecka/chrome-shortkeys#1]
Saying, not compatible with Firefox  55.0.2 ...

**Comment by ArfyFR** [comment]
Hi, same problem with Firefox 55.0.3.

**Comment by pmalecka** [comment]
This will get resolved with version 2.0.20, that is available right now.
Would you be able to give it a shot now?

**Comment by ArfyFR** [comment]
Hi, it is working now, thanks.

One remark: for special keys, all have to be lowercase to work.  And it's not written in the Help
I faced a "F4" not working as it should be "f4" ;)

**Comment by pmalecka** [comment]
Oh, great! Thanks for the tip, I'll include that into the Help.
