### ISSUE TITLE
CMD+⇑ for "Go forward"

### ISSUE THREAD

**Issue by andreasemer** [pmalecka/chrome-shortkeys#15]
I wanted to bind the shortcut "CMD+⇑" to the command "Go forward" and have tried the following combinations for the shortcut:

CMD+↑
CMD+⇑
⌘+⇑
⌘+↑
⌘+up
⌘+UP
CMD+UP
CMD+up

Nothing worked for me. Can you please give me a hint how to bind this shortcut? Im using the latest FF 57 and parallel the DEV Version, with the latest version of the extension with OsX 10.13.1

**Comment by andreasemer** [comment]
The solution is `command+up`

**Comment by pmalecka** [comment]
ah, great stuff, thanks for posting the solution here
