### ISSUE TITLE
Command + [ and Command + ] for Previous, Next Tab

### ISSUE THREAD

**Issue by vk4hdi** [pmalecka/chrome-shortkeys#16]
Hi There

Firstly thank you for recreate this Plugin since upgraded to Firefox 57, killed almost every plugin that i am using.

since very early I have pointed my Command + [ and Command + ] (Mac), Would be Ctrl + [ and Ctrl + ] on Windows to switch between tabs.

Its the plugin does work with this combination, but it works on Alt (Option) + [ and Alt (Option) + ], however the fingers is not handy as Command + [.

Looking forwarding for a solutions!

Thank you again!

**Comment by pmalecka** [comment]
Hi vk4hdi,
ctrl+] (no spaces) seems to work fine for me. Can you confirm you do not have site filter enabled in "Activation Settings..." "Websites: All sites" sohuld be selected.

Perhaps, some other extension is catching the event, colud you try this on a new blank profile?

Thanks,
Peter

**Comment by vk4hdi** [comment]
Hi Peter

Thank you for quick response, 

Under the Navigation Section, it seems Command+[ and Command+] is assigned to "Back" & "Forward", it seems the plugin is unable to overwrite. (but I used another plugin which can overwrite in older version of Firefox, but no longer available.

https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly 

Do you have any idea?

Thank you

**Comment by pmalecka** [comment]
Hi vk4hdi,

unfortunately, I do not have a mac available to test this.

If you press command+] without the extension enabled, does it navigate forward? If it does, then it's a firefox shortcut that we are probably unable to override (API Limitation mentioned in other bugs as well).

Just for the fun of it - try these combinations to see if any of those work.: 
ctrl+]
meta+]
command+]

Do not forget to reload the tab or better - restart firefox after changing the extenstion settings.

Best,
Peter

**Comment by vk4hdi** [comment]
Hi Peter

Yes, It works! but it seems couple bug you may want to know

Once "switched" to a blank tab, the function stops working

if user is typing text in the textfield (form) the function stops working, its trying to behaving in the text box

:)

Thanks!!

Alex

**Comment by pmalecka** [comment]
Hi Alex,
cool!

the blank tab issue is limitation of the API.

The input is a "feature" used for single key shortcuts. You can disable the behavior by ticking the "Activate while in Form fields" in Activation settings of the shortcut.

**Comment by vk4hdi** [comment]
Hi Peter

Thanks! any chance to activate while in the URL location bar?

:)

**Comment by pmalecka** [comment]
Not that I know of, the Firefox API does not support this.
