### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by Keith94** [pmalecka/chrome-shortkeys#2]
I tried assigning various keys (Q, W, F1, F2) to the previous tab and next tab, but it doesn't work at all.

**Comment by pmalecka** [comment]
Hi Keith94,

did you try restarting firefox first? Would you be able to try with different keys (1, 2 in the number row)
Thanks,
Peter

**Comment by Keith94** [comment]
Yes, the number keys work. Any chance to make function keys work?

**Comment by pmalecka** [comment]
As [ArfyFR](https://github.com/ArfyFR)noted: One remark: for special keys, all have to be lowercase to work. And it's not written in the Help
I faced a "F4" not working as it should be "f4" ;)

Could you git this a shot?

**Comment by Keith94** [comment]
Okay, the lowercase letter worked for me too. :) Not sure why it wasn't working before. Thanks!
