### ISSUE TITLE
Add-ons Manager shows Chrome extension and author info

### ISSUE THREAD

**Issue by Luke-Baker** [pmalecka/chrome-shortkeys#25]
On the add-on's options/preferences page,
* Below "Last updated", title says "Shortkeys for Chrome".
* Above the Disable button, it says "Questions or comments or bugs? Email me." with a link to the Chrome extension author's address.

Also, there's a typo in the description on the Firefox Add-ons site: `lishortkeys cannot override…`

**Comment by pmalecka** [comment]
Thanks for reporting this. I have fixed the AMO description. The Documentation links will get updated with the next version coming to AMO.
