### ISSUE TITLE
Request: Getting shortkeys to open bookmark/favorites in a new tab

### ISSUE THREAD

**Issue by pacman00700** [pmalecka/chrome-shortkeys#27]
Hi
Hoping to adopt this extension to replace Sitelauncher- https://addons.mozilla.org/en-US/firefox/addon/sitelauncher/ which doesnt work on FF57 and want to include an option to launch the bookmark in a new tab.
Can we get that please?

**Comment by mikecrittenden** [comment]
FWIW this feature exists in the Chrome version now - just needs to be merged/released in the FF version @pmalecka.

See https://github.com/mikecrittenden/chrome-shortkeys/commit/78536ffab231f586ff0d6855b4386e2d15382ba8 and https://github.com/mikecrittenden/chrome-shortkeys/commit/d12f1f92ad0e34305b738eb5cce320c0ef838815.

**Comment by pmalecka** [comment]
yup, a new version is coming to AMO - based on Mike's Repo.
