### ISSUE TITLE
Excessive permissions?

### ISSUE THREAD

**Issue by frivoal** [pmalecka/chrome-shortkeys#3]
This add-on requires a lot of permissions that don't seem obviously needed.

Could you either scale back to something more reasonable, or but an explainer of why you need this much?

**Comment by DBX12** [comment]
I support this. This excessive amount of permissions scares users away

**Comment by pmalecka** [comment]
As far as I understand (note this is forked from the Chrome extension). These permissions are necessary to support all the actions this extension provides.
I hve not had a chance to look into validating each and every permission against the actions.
Feel free to submit a PR / Go through the process.

**Comment by mikecrittenden** [comment]
I just posted some docs about the permissions required to the upstream (Chrome) repo. See https://github.com/mikecrittenden/chrome-shortkeys/wiki/FAQs-and-Troubleshooting#why-are-all-these-permissions-required

**Comment by pmalecka** [comment]
I'm closing this, since there is not activity here.
