### ISSUE TITLE
Shortcuts don't work on a new tab page

### ISSUE THREAD

**Issue by ccheek21** [pmalecka/chrome-shortkeys#4]
On a new tab page, shortcuts such as "next tab" don't work when the active page is the new tab page.

**Comment by pmalecka** [comment]
That seems to be a limitation of Firefox Web Extensions, I'm afraid there is not much that I can do for now.

**Comment by ccheek21** [comment]
Yeah, I dug into it a bit myself. It looks like there is a [keyboard shortcut API](https://github.com/Koushien/keyboard-shortcut-api) addition in the works, so I guess I'll have to wait until then. Thanks for porting this in the meantime!
