### ISSUE TITLE
Cannot block Ctrl-Q shortcut

### ISSUE THREAD

**Issue by legendre6891** [pmalecka/chrome-shortkeys#6]
I would like to disable `ctrl-q` as a keyboard shortcut to quit Firefox (57 beta).

I set `ctrl+q` to do nothing in the plugin preferences, but `ctrl-q` still quits the browser.

**Comment by pmalecka** [comment]
This does not seem to be possible at the moment. The current Firefox API does not have support for overriding Firefox keyboard shortcuts.

**Comment by pmalecka** [comment]
I looked into this a bit more in depth, can you confirm that this does not work in the context of a webpage ( e.g. click into a webpage before pressing the key combo)?
I can apparently block some actions such as ctrl+j, but not others: ctrl+w. I am guessing some Firefox shortcuts just have higher priority than the webpage.

**Comment by legendre6891** [comment]
Thanks; I can confirm that Ctrl+q does not work in the context of a webpage.
