### ISSUE TITLE
Cannot disable CTRL+J shortcut either

### ISSUE THREAD

**Issue by maverick74** [pmalecka/chrome-shortkeys#9]
Cannot disable CTRL+J shortcut either

**Comment by pmalecka** [comment]
Hi Maverick74, I've got the same answer here: this does not seem to be possible at the moment. The current Firefox API does not have support for overriding Firefox keyboard shortcuts.

**Comment by maverick74** [comment]
The current Firefox API really is a great piece of $hit, isn't it... I say this because almost everywhere i turn i get the same answer.......

i guess it'll take years to get to the old addons "power"... if ever...

Anyway, thank you so much for your reply and your work on this addon :)

**Comment by maverick74** [comment]
The current Firefox API really is a great piece of $hit, isn't it... I say this because almost everywhere i turn i get the same answer.......

i guess it'll take years to get to the old addons "power"... if ever...

Anyway, thank you so much for your reply and your work on this addon :)
